// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function route_score(r) {
  if (r) {
    var switcher = r[2] - 1 | 0;
    if (switcher > 5 || switcher < 0) {
      return Pervasives.failwith("Not possible; deal with later");
    } else {
      switch (switcher) {
        case 0 : 
            return 1;
        case 1 : 
            return 2;
        case 2 : 
            return 4;
        case 3 : 
            return 7;
        case 4 : 
            return 10;
        case 5 : 
            return 15;
        
      }
    }
  } else {
    return 0;
  }
}

function is_taken(r) {
  if (r) {
    return true;
  } else {
    return false;
  }
}

exports.route_score = route_score;
exports.is_taken = is_taken;
/* No side effect */
