// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Random = require("bs-platform/lib/js/random.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function remove_n(n, lst) {
  if (n > List.length(lst)) {
    return lst;
  } else if (lst) {
    var t = lst[1];
    if (n === 0) {
      return t;
    } else {
      return /* :: */[
              lst[0],
              remove_n(n - 1 | 0, t)
            ];
    }
  } else {
    return /* [] */0;
  }
}

function random_int(n) {
  try {
    return Random.$$int(n);
  }
  catch (raw_exn){
    var exn = Js_exn.internalToOCamlException(raw_exn);
    if (exn[0] === Caml_builtin_exceptions.invalid_argument) {
      return 0;
    } else {
      throw exn;
    }
  }
}

function shuffler(_from, _to_list, _len) {
  while(true) {
    var len = _len;
    var to_list = _to_list;
    var from = _from;
    if (len !== 0) {
      var i = random_int(len);
      _len = len - 1 | 0;
      _to_list = /* :: */[
        List.nth(from, i),
        to_list
      ];
      _from = remove_n(i, from);
      continue ;
    } else {
      return to_list;
    }
  };
}

function drop(_n, _lst) {
  while(true) {
    var lst = _lst;
    var n = _n;
    if (n === 0) {
      return lst;
    } else if (lst) {
      _lst = lst[1];
      _n = n - 1 | 0;
      continue ;
    } else {
      return /* [] */0;
    }
  };
}

function shuffle(tr, _) {
  var shuf = shuffler(tr, /* [] */0, List.length(tr));
  return /* tuple */[
          shuf,
          /* [] */0
        ];
}

function draw_card(_t, tr) {
  while(true) {
    var t = _t;
    if (t !== /* [] */0) {
      return /* tuple */[
              /* :: */[
                List.hd(t),
                /* [] */0
              ],
              List.tl(t)
            ];
    } else {
      var shuff = shuffle(tr, t);
      _t = shuff[0];
      continue ;
    }
  };
}

function discard(c, tr) {
  return /* :: */[
          c,
          tr
        ];
}

var init_deck = shuffle(/* :: */[
        /* Red */0,
        /* :: */[
          /* Red */0,
          /* :: */[
            /* Red */0,
            /* :: */[
              /* Red */0,
              /* :: */[
                /* Red */0,
                /* :: */[
                  /* Red */0,
                  /* :: */[
                    /* Red */0,
                    /* :: */[
                      /* Red */0,
                      /* :: */[
                        /* Red */0,
                        /* :: */[
                          /* Red */0,
                          /* :: */[
                            /* Red */0,
                            /* :: */[
                              /* Red */0,
                              /* :: */[
                                /* Green */1,
                                /* :: */[
                                  /* Green */1,
                                  /* :: */[
                                    /* Green */1,
                                    /* :: */[
                                      /* Green */1,
                                      /* :: */[
                                        /* Green */1,
                                        /* :: */[
                                          /* Green */1,
                                          /* :: */[
                                            /* Green */1,
                                            /* :: */[
                                              /* Green */1,
                                              /* :: */[
                                                /* Green */1,
                                                /* :: */[
                                                  /* Green */1,
                                                  /* :: */[
                                                    /* Green */1,
                                                    /* :: */[
                                                      /* Green */1,
                                                      /* :: */[
                                                        /* Blue */2,
                                                        /* :: */[
                                                          /* Blue */2,
                                                          /* :: */[
                                                            /* Blue */2,
                                                            /* :: */[
                                                              /* Blue */2,
                                                              /* :: */[
                                                                /* Blue */2,
                                                                /* :: */[
                                                                  /* Blue */2,
                                                                  /* :: */[
                                                                    /* Blue */2,
                                                                    /* :: */[
                                                                      /* Blue */2,
                                                                      /* :: */[
                                                                        /* Blue */2,
                                                                        /* :: */[
                                                                          /* Blue */2,
                                                                          /* :: */[
                                                                            /* Blue */2,
                                                                            /* :: */[
                                                                              /* Blue */2,
                                                                              /* :: */[
                                                                                /* Yellow */3,
                                                                                /* :: */[
                                                                                  /* Yellow */3,
                                                                                  /* :: */[
                                                                                    /* Yellow */3,
                                                                                    /* :: */[
                                                                                      /* Yellow */3,
                                                                                      /* :: */[
                                                                                        /* Yellow */3,
                                                                                        /* :: */[
                                                                                          /* Yellow */3,
                                                                                          /* :: */[
                                                                                            /* Yellow */3,
                                                                                            /* :: */[
                                                                                              /* Yellow */3,
                                                                                              /* :: */[
                                                                                                /* Yellow */3,
                                                                                                /* :: */[
                                                                                                  /* Yellow */3,
                                                                                                  /* :: */[
                                                                                                    /* Yellow */3,
                                                                                                    /* :: */[
                                                                                                      /* Yellow */3,
                                                                                                      /* :: */[
                                                                                                        /* Pink */4,
                                                                                                        /* :: */[
                                                                                                          /* Pink */4,
                                                                                                          /* :: */[
                                                                                                            /* Pink */4,
                                                                                                            /* :: */[
                                                                                                              /* Pink */4,
                                                                                                              /* :: */[
                                                                                                                /* Pink */4,
                                                                                                                /* :: */[
                                                                                                                  /* Pink */4,
                                                                                                                  /* :: */[
                                                                                                                    /* Pink */4,
                                                                                                                    /* :: */[
                                                                                                                      /* Pink */4,
                                                                                                                      /* :: */[
                                                                                                                        /* Pink */4,
                                                                                                                        /* :: */[
                                                                                                                          /* Pink */4,
                                                                                                                          /* :: */[
                                                                                                                            /* Pink */4,
                                                                                                                            /* :: */[
                                                                                                                              /* Pink */4,
                                                                                                                              /* :: */[
                                                                                                                                /* Orange */5,
                                                                                                                                /* :: */[
                                                                                                                                  /* Orange */5,
                                                                                                                                  /* :: */[
                                                                                                                                    /* Orange */5,
                                                                                                                                    /* :: */[
                                                                                                                                      /* Orange */5,
                                                                                                                                      /* :: */[
                                                                                                                                        /* Orange */5,
                                                                                                                                        /* :: */[
                                                                                                                                          /* Orange */5,
                                                                                                                                          /* :: */[
                                                                                                                                            /* Orange */5,
                                                                                                                                            /* :: */[
                                                                                                                                              /* Orange */5,
                                                                                                                                              /* :: */[
                                                                                                                                                /* Orange */5,
                                                                                                                                                /* :: */[
                                                                                                                                                  /* Orange */5,
                                                                                                                                                  /* :: */[
                                                                                                                                                    /* Orange */5,
                                                                                                                                                    /* :: */[
                                                                                                                                                      /* Orange */5,
                                                                                                                                                      /* :: */[
                                                                                                                                                        /* White */6,
                                                                                                                                                        /* :: */[
                                                                                                                                                          /* White */6,
                                                                                                                                                          /* :: */[
                                                                                                                                                            /* White */6,
                                                                                                                                                            /* :: */[
                                                                                                                                                              /* White */6,
                                                                                                                                                              /* :: */[
                                                                                                                                                                /* White */6,
                                                                                                                                                                /* :: */[
                                                                                                                                                                  /* White */6,
                                                                                                                                                                  /* :: */[
                                                                                                                                                                    /* White */6,
                                                                                                                                                                    /* :: */[
                                                                                                                                                                      /* White */6,
                                                                                                                                                                      /* :: */[
                                                                                                                                                                        /* White */6,
                                                                                                                                                                        /* :: */[
                                                                                                                                                                          /* White */6,
                                                                                                                                                                          /* :: */[
                                                                                                                                                                            /* White */6,
                                                                                                                                                                            /* :: */[
                                                                                                                                                                              /* White */6,
                                                                                                                                                                              /* :: */[
                                                                                                                                                                                /* Black */7,
                                                                                                                                                                                /* :: */[
                                                                                                                                                                                  /* Black */7,
                                                                                                                                                                                  /* :: */[
                                                                                                                                                                                    /* Black */7,
                                                                                                                                                                                    /* :: */[
                                                                                                                                                                                      /* Black */7,
                                                                                                                                                                                      /* :: */[
                                                                                                                                                                                        /* Black */7,
                                                                                                                                                                                        /* :: */[
                                                                                                                                                                                          /* Black */7,
                                                                                                                                                                                          /* :: */[
                                                                                                                                                                                            /* Black */7,
                                                                                                                                                                                            /* :: */[
                                                                                                                                                                                              /* Black */7,
                                                                                                                                                                                              /* :: */[
                                                                                                                                                                                                /* Black */7,
                                                                                                                                                                                                /* :: */[
                                                                                                                                                                                                  /* Black */7,
                                                                                                                                                                                                  /* :: */[
                                                                                                                                                                                                    /* Black */7,
                                                                                                                                                                                                    /* :: */[
                                                                                                                                                                                                      /* Black */7,
                                                                                                                                                                                                      /* :: */[
                                                                                                                                                                                                        /* Wild */8,
                                                                                                                                                                                                        /* :: */[
                                                                                                                                                                                                          /* Wild */8,
                                                                                                                                                                                                          /* :: */[
                                                                                                                                                                                                            /* Wild */8,
                                                                                                                                                                                                            /* :: */[
                                                                                                                                                                                                              /* Wild */8,
                                                                                                                                                                                                              /* :: */[
                                                                                                                                                                                                                /* Wild */8,
                                                                                                                                                                                                                /* :: */[
                                                                                                                                                                                                                  /* Wild */8,
                                                                                                                                                                                                                  /* :: */[
                                                                                                                                                                                                                    /* Wild */8,
                                                                                                                                                                                                                    /* :: */[
                                                                                                                                                                                                                      /* Wild */8,
                                                                                                                                                                                                                      /* :: */[
                                                                                                                                                                                                                        /* Wild */8,
                                                                                                                                                                                                                        /* :: */[
                                                                                                                                                                                                                          /* Wild */8,
                                                                                                                                                                                                                          /* :: */[
                                                                                                                                                                                                                            /* Wild */8,
                                                                                                                                                                                                                            /* :: */[
                                                                                                                                                                                                                              /* Wild */8,
                                                                                                                                                                                                                              /* :: */[
                                                                                                                                                                                                                                /* Wild */8,
                                                                                                                                                                                                                                /* :: */[
                                                                                                                                                                                                                                  /* Wild */8,
                                                                                                                                                                                                                                  /* [] */0
                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                              ]
                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                          ]
                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                      ]
                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                  ]
                                                                                                                                                                                                                ]
                                                                                                                                                                                                              ]
                                                                                                                                                                                                            ]
                                                                                                                                                                                                          ]
                                                                                                                                                                                                        ]
                                                                                                                                                                                                      ]
                                                                                                                                                                                                    ]
                                                                                                                                                                                                  ]
                                                                                                                                                                                                ]
                                                                                                                                                                                              ]
                                                                                                                                                                                            ]
                                                                                                                                                                                          ]
                                                                                                                                                                                        ]
                                                                                                                                                                                      ]
                                                                                                                                                                                    ]
                                                                                                                                                                                  ]
                                                                                                                                                                                ]
                                                                                                                                                                              ]
                                                                                                                                                                            ]
                                                                                                                                                                          ]
                                                                                                                                                                        ]
                                                                                                                                                                      ]
                                                                                                                                                                    ]
                                                                                                                                                                  ]
                                                                                                                                                                ]
                                                                                                                                                              ]
                                                                                                                                                            ]
                                                                                                                                                          ]
                                                                                                                                                        ]
                                                                                                                                                      ]
                                                                                                                                                    ]
                                                                                                                                                  ]
                                                                                                                                                ]
                                                                                                                                              ]
                                                                                                                                            ]
                                                                                                                                          ]
                                                                                                                                        ]
                                                                                                                                      ]
                                                                                                                                    ]
                                                                                                                                  ]
                                                                                                                                ]
                                                                                                                              ]
                                                                                                                            ]
                                                                                                                          ]
                                                                                                                        ]
                                                                                                                      ]
                                                                                                                    ]
                                                                                                                  ]
                                                                                                                ]
                                                                                                              ]
                                                                                                            ]
                                                                                                          ]
                                                                                                        ]
                                                                                                      ]
                                                                                                    ]
                                                                                                  ]
                                                                                                ]
                                                                                              ]
                                                                                            ]
                                                                                          ]
                                                                                        ]
                                                                                      ]
                                                                                    ]
                                                                                  ]
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ], /* [] */0)[0];

var TrainDeck = /* module */[
  /* draw_card */draw_card,
  /* shuffle */shuffle,
  /* discard */discard,
  /* init_deck */init_deck,
  /* init_trash : [] */0
];

function shuffle$1(tr, _) {
  var shuf = shuffler(tr, /* [] */0, List.length(tr));
  return /* tuple */[
          shuf,
          /* [] */0
        ];
}

function draw_card$1(_t, tr) {
  while(true) {
    var t = _t;
    if (t !== /* [] */0) {
      return /* tuple */[
              /* :: */[
                List.hd(t),
                /* :: */[
                  List.nth(t, 1),
                  /* :: */[
                    List.nth(t, 2),
                    /* [] */0
                  ]
                ]
              ],
              drop(3, t)
            ];
    } else {
      var shuff = shuffle$1(tr, t);
      _t = shuff[0];
      continue ;
    }
  };
}

function discard$1(c, tr) {
  return /* :: */[
          c,
          tr
        ];
}

var init_deck$1 = shuffle$1(/* :: */[
        /* record */[
          /* loc1 */"Bailey Hall",
          /* loc2 */"Dairy Bar",
          /* points */12
        ],
        /* :: */[
          /* record */[
            /* loc1 */"McGraw Tower",
            /* loc2 */"Eddy Gate",
            /* points */8
          ],
          /* :: */[
            /* record */[
              /* loc1 */"Appel Commons",
              /* loc2 */"Schoellkopf Field",
              /* points */13
            ],
            /* :: */[
              /* record */[
                /* loc1 */"RPCC",
                /* loc2 */"Duffield Hall",
                /* points */12
              ],
              /* :: */[
                /* record */[
                  /* loc1 */"House Becker",
                  /* loc2 */"Appel Commons",
                  /* points */20
                ],
                /* :: */[
                  /* record */[
                    /* loc1 */"Kennedy Hall",
                    /* loc2 */"Olin Hall",
                    /* points */9
                  ],
                  /* :: */[
                    /* record */[
                      /* loc1 */"Martha Van Rensselaer Hall",
                      /* loc2 */"Teagle Hall",
                      /* points */6
                    ],
                    /* :: */[
                      /* record */[
                        /* loc1 */"House Bethe",
                        /* loc2 */"Eddy Gate",
                        /* points */9
                      ],
                      /* :: */[
                        /* record */[
                          /* loc1 */"Eddy Gate",
                          /* loc2 */"Kennedy Hall",
                          /* points */16
                        ],
                        /* :: */[
                          /* record */[
                            /* loc1 */"Noyes Community Center",
                            /* loc2 */"Eddy Gate",
                            /* points */11
                          ],
                          /* :: */[
                            /* record */[
                              /* loc1 */"Risley",
                              /* loc2 */"Cornell Health",
                              /* points */7
                            ],
                            /* :: */[
                              /* record */[
                                /* loc1 */"Appel Commons",
                                /* loc2 */"Teagle Hall",
                                /* points */9
                              ],
                              /* :: */[
                                /* record */[
                                  /* loc1 */"Risley",
                                  /* loc2 */"Eddy Gate",
                                  /* points */13
                                ],
                                /* :: */[
                                  /* record */[
                                    /* loc1 */"RPCC",
                                    /* loc2 */"Gates Hall",
                                    /* points */11
                                  ],
                                  /* :: */[
                                    /* record */[
                                      /* loc1 */"Physical Sciences Building",
                                      /* loc2 */"Duffield Hall",
                                      /* points */8
                                    ],
                                    /* :: */[
                                      /* record */[
                                        /* loc1 */"Uris Hall",
                                        /* loc2 */"Duffield Hall",
                                        /* points */5
                                      ],
                                      /* :: */[
                                        /* record */[
                                          /* loc1 */"Eddy Gate",
                                          /* loc2 */"Martha Van Rensselaer Hall",
                                          /* points */21
                                        ],
                                        /* :: */[
                                          /* record */[
                                            /* loc1 */"Schwartz Center",
                                            /* loc2 */"Teagle Hall",
                                            /* points */17
                                          ],
                                          /* :: */[
                                            /* record */[
                                              /* loc1 */"Willard Straight Hall",
                                              /* loc2 */"Mann Library",
                                              /* points */11
                                            ],
                                            /* :: */[
                                              /* record */[
                                                /* loc1 */"Noyes Community Center",
                                                /* loc2 */"Ives Hall",
                                                /* points */17
                                              ],
                                              /* :: */[
                                                /* record */[
                                                  /* loc1 */"House Becker",
                                                  /* loc2 */"Olin Hall",
                                                  /* points */13
                                                ],
                                                /* :: */[
                                                  /* record */[
                                                    /* loc1 */"Kennedy Hall",
                                                    /* loc2 */"Schoellkopf Field",
                                                    /* points */12
                                                  ],
                                                  /* :: */[
                                                    /* record */[
                                                      /* loc1 */"Willard Straight Hall",
                                                      /* loc2 */"Carpenter Hall",
                                                      /* points */4
                                                    ],
                                                    /* :: */[
                                                      /* record */[
                                                        /* loc1 */"Physical Sciences Building",
                                                        /* loc2 */"Carpetner Hall",
                                                        /* points */10
                                                      ],
                                                      /* :: */[
                                                        /* record */[
                                                          /* loc1 */"Helen Newman Hall",
                                                          /* loc2 */"Ives Hall",
                                                          /* points */12
                                                        ],
                                                        /* :: */[
                                                          /* record */[
                                                            /* loc1 */"Eddy Gate",
                                                            /* loc2 */"Dairy Bar",
                                                            /* points */20
                                                          ],
                                                          /* :: */[
                                                            /* record */[
                                                              /* loc1 */"Warren Hall",
                                                              /* loc2 */"Dairy Bar",
                                                              /* points */10
                                                            ],
                                                            /* :: */[
                                                              /* record */[
                                                                /* loc1 */"Rhodes Hall",
                                                                /* loc2 */"Martha Van Rensselaer Hall",
                                                                /* points */11
                                                              ],
                                                              /* :: */[
                                                                /* record */[
                                                                  /* loc1 */"House Bethe",
                                                                  /* loc2 */"Martha Van Rensselaer Hall",
                                                                  /* points */22
                                                                ],
                                                                /* :: */[
                                                                  /* record */[
                                                                    /* loc1 */"Helen Newman Hall",
                                                                    /* loc2 */"Statler Hall",
                                                                    /* points */9
                                                                  ],
                                                                  /* [] */0
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ], /* [] */0)[0];

var DestinationDeck = /* module */[
  /* draw_card */draw_card$1,
  /* shuffle */shuffle$1,
  /* discard */discard$1,
  /* init_deck */init_deck$1,
  /* init_trash : [] */0
];

exports.TrainDeck = TrainDeck;
exports.DestinationDeck = DestinationDeck;
/* init_deck Not a pure module */
