// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var State = require("./state.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function ai_move() {
  return Pervasives.failwith("Unimplemented");
}

exports.ai_move = ai_move;
/* State Not a pure module */
