// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Ai = require("./ai.bs.js");
var Board = require("./board.bs.js");
var State = require("./state.bs.js");
var Player = require("./player.bs.js");
var Components = require("./components.bs.js");

var CheckState = /* State */[
  State.init_state,
  State.current_player_turn,
  State.draw_card,
  State.take_route,
  State.decided_routes,
  State.place_on_board,
  State.score,
  State.routes,
  State.longest_route
];

var CheckComponent = /* Components */[
  Components.TrainDeck,
  Components.DestinationDeck
];

var CheckPlayer = [
  Player.destination_tickets,
  Player.train_cards,
  Player.score,
  Player.trains_remaining
];

var CheckBoard = /* Board */[
  Board.route_score,
  Board.is_taken
];

var CheckAI = /* Ai */[Ai.ai_move];

exports.CheckState = CheckState;
exports.CheckComponent = CheckComponent;
exports.CheckPlayer = CheckPlayer;
exports.CheckBoard = CheckBoard;
exports.CheckAI = CheckAI;
/* State Not a pure module */
