// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function destination_tickets() {
  return Pervasives.failwith("hahaha");
}

function update_destination_tickets(_, _$1) {
  return Pervasives.failwith("hahaha");
}

var train_cards = Pervasives.failwith("hahaha");

var score = Pervasives.failwith("hahaha");

var trains_remaining = Pervasives.failwith("hahaha");

var init_players = Pervasives.failwith("hahaha");

exports.destination_tickets = destination_tickets;
exports.update_destination_tickets = update_destination_tickets;
exports.train_cards = train_cards;
exports.score = score;
exports.trains_remaining = trains_remaining;
exports.init_players = init_players;
/* train_cards Not a pure module */
